version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ec2-user/Petclinic
    overwrite: yes
file_exists_behavior: OVERWRITE

permissions:
  - object: /
    pattern: "**"
    owner: root
    group: root
    mode: 755

hooks:
  ApplicationStart:
    - location: scripts/runApp.sh
      timeout: 60
      runas: root
